---
title: "resource_comp"
author: "ZZ"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    code_folding: hide
    toc: true
    toc_depth: 3
    number_sections: true
    toc_float:
      collapsed: no
      smooth_scroll: no
---

```{r}
knitr::opts_chunk$set(message = F,warning = F)
```


```{r}
library(tidyverse)
library(Taxonstand)
library(nlme)
library(lme4)
library(lmerTest)
library(knitr)
library(kableExtra)
```

# read data
```{r}
dat_yj_raw <- read.csv('Data_ABcomp_HFJ.csv')
dat_zz <- read.csv('Konstanz.csv')
colnames(dat_zz) <- colnames(dat_zz) %>% tolower()

dat_yj <- dat_yj_raw %>% 
  dplyr::select(Nr., Target_Species, Target_Status, Competition, Competitor_Species, Competitor_Status,
         N_Treatment, Shading_Treatment,
         Target_Shoot, Competitor_Shoot)

```


```{r}
# make pots with two data points into two rows
dat_yj_t <- dat_yj %>% # target individuals
  dplyr::select(-Competitor_Shoot) %>% 
  rename(biomass = Target_Shoot,
         target  = Target_Species,
         status  = Target_Status,
         comp        = Competitor_Species,
         status_comp = Competitor_Status,
         comp_treat  = Competition ,
         fert  = N_Treatment,
         light =  Shading_Treatment,
         id = Nr.)

dat_yj_c <- dat_yj %>% # competitors
  dplyr::select(-Target_Shoot) %>% 
  rename(biomass = Competitor_Shoot,
         target  = Competitor_Species,
         status  = Competitor_Status,
         comp        = Target_Species,
         status_comp = Target_Status,
         comp_treat  = Competition ,
         fert  = N_Treatment,
         light =  Shading_Treatment,
         id = Nr.)
dat_yj <- rbind(dat_yj_t, dat_yj_c) %>% 
  filter(status != 'Without') %>% 
  mutate(status = ifelse(status == 'Self', as.character(status_comp), as.character(status))#,
         #status_comp = ifelse(status_comp == 'Self', as.character(status), as.character(status_comp)),
         ) %>% 
  #----- change names ---------#
  mutate(status      = fct_recode(status, 'alien' = 'Invasive', 'native' = 'Native'),
         status_comp = fct_recode(status_comp, 'alien' = 'Invasive', 'native' = 'Native',
                                  'intra' = 'Self', 'alone' = 'Without'),
         light      = fct_recode(light, 'Ambient' = 'Control'),
         comp_treat = tolower(comp_treat),
         comp = ifelse(comp == 'No_competitor', 'Non', as.character(comp))
         ) %>% 
  #----- change reference levels -------#
  mutate(light = fct_relevel(light, 'Shading'),
         fert = fct_relevel(fert, 'Low')) %>% 
  droplevels()

# remove pots contained dead (NA) plants
list <- dat_yj$id[is.na(dat_yj$biomass)] %>% unique
dat_yj <- dat_yj %>% 
  filter(!id %in% list)

sp_list <-dat_yj$target %>% unique %>% str_replace('_', ' ')
sp_list <- TPL(sp_list) %>% 
  dplyr::select(Taxon, Family) %>% 
  mutate(Taxon = str_replace(Taxon, ' ', '_')) 
dat_yj <- dat_yj %>% 
  left_join(sp_list, by = c('target' = 'Taxon')) %>% 
  rename(family_tar = Family) %>% 
  left_join(sp_list, by = c('comp' = 'Taxon')) %>% 
  rename(family_comp = Family) %>% 
  mutate(family_comp = ifelse(is.na(family_comp), 'Non', as.character(family_comp)))
rm(sp_list, list, dat_yj_c, dat_yj_t)
```


```{r}
dat_zz <- dat_zz %>% 
  mutate(status = fct_recode(status, 'alien' = 'ex', 'native' = 'nat'),
         light  = fct_recode(light, 'Ambient' = 'W', 'Shading' = 'G'),
         fert   = fct_recode(fert , 'High' = 'H', 'Low' = 'L'),
         target = str_remove(target, '\\s\\(\\w*\\)'), # remove (***)
         comp   = str_remove(comp, '\\s\\(\\w*\\)'),
         target = str_replace(target, '\\s', '_'),
         comp   = str_replace(comp, '\\s', '_')
         ) %>% 
  #----- change reference levels -------#
  mutate(light = fct_relevel(light, 'Shading'),
         fert = fct_relevel(fert, 'Low')) %>% 
  droplevels()
```


merge two datasets
```{r}
dat <- dat_yj %>% 
  filter(as.character(status) != as.character(status_comp)) %>% # exclude native-native, and alien-alien combs
  dplyr::select(-status_comp) %>% 
  bind_rows(dat_zz) %>% 
  mutate(exp = str_extract(id, '^.'))

```




# analyses

```{r}
## add contrast for alone vs competition and intra vs inter competition
mat <- matrix(c(1/3, 1/3, 1/3,  
                -1,  0.5, 0.5,
                0,     1, -1), ncol=3)

mat_solve = solve(t(mat))[,2:3] %>% 
  as.data.frame() %>% 
  mutate(comp_treat = c('alone', 'inter', 'intra')) %>% 
  rename(T_alone_comp = V1,
         T_intra_inter = V2)
dat <- dat %>% 
  left_join(mat_solve)
rm(mat)
```


## only native-alien, two dataset pooled

lme
```{r}
u <- rep(1, nrow(dat))
dat <- dat %>% 
  mutate(light_slope = paste(target, light, sep = '_'),
         fert_slope = paste(target, fert, sep = '_'))
m0 <- lme(log(biomass) ~ status*(T_alone_comp + T_intra_inter) * fert * light, # + length_in_mm
          random=list(u = pdBlocked(list(
            pdIdent(form = ~ exp-1),
            pdIdent(form = ~ family_tar-1),
            pdIdent(form = ~ target-1),
            pdIdent(form = ~ light_slope -1),
            pdIdent(form = ~ family_comp-1),
            pdIdent(form = ~ comp-1)
            ))),
          weights = varComb(varIdent(form= ~1|target),
                            varIdent(form= ~1|comp_treat)),
          control = lmeControl(msMaxIter = 10000, msMaxEval = 10000),
          data=dat)



m2 <- update(m0,
            random=list(u = pdBlocked(list(
                                          pdIdent(form = ~ exp-1),
                                          pdIdent(form = ~ family_tar-1),
                                          pdIdent(form = ~ target-1),
                                          pdIdent(form = ~ light_slope -1), # similar to random slope
                                          pdIdent(form = ~ fert_slope -1),  # similar to random slope
                                          pdIdent(form = ~ family_comp-1),
                                          pdIdent(form = ~ comp-1)))))



m2 %>% Ftable
```


lmer
```{r, eval = F}
# dat$obs <- as.factor(1:nrow(dat))
# m <- lmer(log(biomass) ~ status*(T_alone_comp + T_intra_inter) * fert * light +
#            #(light + fert|target) + (1|comp) + (1|family_tar) + (1|family_comp) #+ 
#            (fert + light|target) + (1|family_tar)  + (1|comp) + (1|family_comp) + (1|exp)#+ 
#            #(target - 1|obs) # allow different variances
#           ,
#           control=lmerControl(#optimizer ="Nelder_Mead",
#                               check.nobs.vs.nRE  = "ignore",
#                               check.nobs.vs.nlev = "ignore"),
#          data = dat)
```

brms (similar results)
```{r, eval = F}
formula <- bf(log(biomass) ~ status*(T_alone_comp + T_intra_inter) * fert * light + 
                (1 + light|target) + (1|family_tar) + (1|comp) + (1|family_comp) + 
                (1 + light|exp)
              ,
              sigma ~ 0 + target)
```


```{r}
# status * fert * light
dat %>% 
  ggplot(aes(x = light, y = log(biomass), fill = status)) +
  geom_boxplot() + facet_wrap(~ fert)

# intra inter
dat %>% 
  filter(comp_treat != 'alone') %>% 
  ggplot(aes(x = comp_treat, y = log(biomass))) + geom_boxplot() + 
  facet_wrap(~ status)

```



## seperately
### zz
```{r}
dat_zz_only <- dat %>% 
  filter(exp == 'A')
```



```{r}
u <- rep(1, nrow(dat_zz_only))
m_zz <- lme(log(biomass) ~ status*(T_alone_comp + T_intra_inter) * fert * light, # + length_in_mm
          random=list(u = pdBlocked(list(
            pdIdent(form = ~ family_tar-1),
            pdIdent(form = ~ target-1),
            pdIdent(form = ~ family_comp-1),
            pdIdent(form = ~ light_slope-1),
            pdIdent(form = ~ fert_slope-1),
            pdIdent(form = ~ comp-1)
            ))),
          weights = varComb(varIdent(form= ~1|target),
                            varIdent(form= ~1|comp_treat)
                            ),
          control = lmeControl(msMaxIter = 100000),
          data=dat_zz_only)
test <- update(m_zz,
               random=list(u = pdBlocked(list(
            pdIdent(form = ~ family_tar-1),
            pdIdent(form = ~ target-1),
            pdIdent(form = ~ family_comp-1),
            pdIdent(form = ~ light_slope-1),
            pdIdent(form = ~ fert_slope-1),
            pdIdent(form = ~ comp-1),
            pdIdent(form = ~ id-1)
            ))))
AIC(m_zz, test)
m_zz %>% Ftable
```





### YJ
```{r}
dat_yj$comp_treat %>% unique
dat_yj$status_comp %>% unique
mat <- matrix(c(1/4, 1/4, 1/4, 1/4,  
                -1,  1/3, 1/3, 1/3, # alone vs comp
                0,   1,   -0.5, -0.5,  # 
                0,   0,   1,  -1), # native vs alien
              ncol = 4)

mat_solve_yj = solve(t(mat))[,2:4] %>% 
  as.data.frame() %>% 
  mutate(status_comp = c('alone', 'intra', 'alien', 'native')) %>% 
  rename(T_alone_comp   = V1,
         T_intra_inter  = V2,
         T_alien_native = V3
         )
dat_yj_only <- dat_yj %>% 
  left_join(mat_solve_yj) %>% 
  mutate(light_slope = paste(target, light, sep = '_'),
         fert_slope = paste(target, fert, sep = '_'))
rm(mat)
```


```{r}
u <- rep(1, nrow(dat_yj_only))
m_yj <- lme(log(biomass) ~ status*(T_alone_comp + T_intra_inter + T_alien_native) * fert * light, # + length_in_mm
            random=list(u = pdBlocked(list(
                                          pdIdent(form = ~ family_tar-1),
                                          pdIdent(form = ~ target-1),
                                          pdIdent(form = ~ family_comp-1),
                                          pdIdent(form = ~ light_slope-1),
                                          pdIdent(form = ~ fert_slope-1),
                                          pdIdent(form = ~ comp-1)
                                          ))),
          weights = varComb(varIdent(form= ~1|target),
                            varIdent(form= ~1|status_comp)
                            ),
          control = lmeControl(msMaxIter = 10000),
          data=dat_yj_only)


test <- update(m_yj, 
               weights = varIdent(form= ~1|target))
```


```{r}
m_yj %>% Ftable
```


# Figures

```{r}
dat_zz_only %>% 
  ggplot(aes(x = fert, y = log(biomass), fill = status)) + geom_boxplot() +
  facet_wrap( ~ light) # T_alone_comp: -0.66666667 alone
dat_zz_only %>% 
  ggplot(aes(x = light, y = log(biomass), fill = status)) + geom_boxplot() 


dat_yj_only %>% 
  ggplot(aes(x = fert, y = log(biomass), fill = status)) + geom_boxplot() +
  facet_wrap( ~ light) 
```





```{r}
dir.create('table', showWarnings = F)
m2 %>% Ftable %>% save_kable('table/pooled.png')
m_zz %>% Ftable %>% save_kable('table/zz_single.png')
m_yj %>% Ftable %>% save_kable('table/yj_single.png')

```

```{r}
save(file = 'data20201102.RData', list = ls())
```

